//API 1
GET http://localhost:3000/todos?status=TO%20DO
Content-Type: application/json

###

GET http://localhost:3000/todos?priority=HIGH
Content-Type: application/json

###
GET http://localhost:3000/todos/?priority=HIGH&status=DONE
Content-Type: application/json

###
GET http://localhost:3000/todos/?search_q=Buy
Content-Type: application/json
###

GET http://localhost:3000/todos/?category=WORKw&status=DONE
Content-Type: application/json

###
GET http://localhost:3000/todos/?category=HOME
Content-Type: application/json

###
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
Content-Type: application/json

###


//API 2
GET http://localhost:3000/todos/6/
Content-Type: application/json

###

//API 3

GET http://localhost:3000/agenda/?date=2021-02-22
Content-Type: application/json

###

//API 4
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}

### 

//API 5
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
    "dueDate": "2021-01-12"
}

###

//API 6
DELETE http://localhost:3000/todos/6/
Content-Type: application/json

###